### ISSUE TITLE
Split parameters

### ISSUE THREAD

**Issue by Callemul** [piotrturski/zohhak#11]
Hello! I liked your lib and included to my project, but...

I have one test case with this annotation. And I have exception. 

`
@TestWith("ф5,9", "ф5.9", "3" )`

![image](https://cloud.githubusercontent.com/assets/18458401/14520797/196b743e-022f-11e6-9fc3-66ae929ccfd6.png)

![image](https://cloud.githubusercontent.com/assets/18458401/14520902/79c5baec-022f-11e6-9019-bfbc8365aadf.png)

I a little debugged your code. 
"ф5,9" is a one of my parameters, it doesn't want to be splitted))

![image](https://cloud.githubusercontent.com/assets/18458401/14520977/df037840-022f-11e6-9461-c5e6b102781b.png)

![image](https://cloud.githubusercontent.com/assets/18458401/14521038/2e71974a-0230-11e6-8eb0-ccbd216b6443.png)

What can I do for you to understand this issue?

**Comment by piotrturski** [comment]
user guide may help: https://github.com/piotrturski/zohhak/blob/master/Full-Guide.md#commas-white-chars-apostrophes
does it solve your problem?

**Comment by Callemul** [comment]
Dear, piotrturski. I'm glad that you are here. It was a good guess. But...

This link says "contains parameter 'separator' ". But I need only one  parameter for my function. And this function must be passed three times by: "ф5,9", "ф5.9", "3". It equal three test cases. The current your link wants create only one test case, when I need three.

Please, look at this my crazy queue (all of them want to be passed by function, where one parameter. One by one they all will be passed to the function):
![image](https://cloud.githubusercontent.com/assets/18458401/14557532/67339dfe-0306-11e6-8844-aa84df855e44.png)

And I must pass strings, where Double might be written  separated by '.' (dot) or ',' (comma). The string don't wants be changed.

Test case #1: $100,5 -> 100.5
Test case #2: $100.5 -> 100.5

Thank you for your attention!

**Comment by piotrturski** [comment]
zohhak splits your input string into parameters using separator. every time it finds a separator it will make a split and therefore create another parameter. the default separator is a comma. if you don't want to split your input, you have two options: remove default separator (comma) from your input or use different separator. the link shows how to do the second

**Comment by Callemul** [comment]
Thanks! I added separator "&"

As for me, the ideal solution is change default comma to "&", because every time I need to write excessive code: `, separator = "&"`

![image](https://cloud.githubusercontent.com/assets/18458401/14561413/cf242696-031e-11e6-831f-d43ad6d684a1.png)

Well, any way, thanks for all! 

It solve my issue for some time. Good luck!

**Comment by piotrturski** [comment]
if you want to avoid copy/pasting  your configuration, user guide may help: https://github.com/piotrturski/zohhak/blob/master/Full-Guide.md#drying-configuration

**Comment by Callemul** [comment]
It was good. Thanks!
