### ISSUE TITLE
best practice passing string value "null"

### ISSUE THREAD

**Issue by codejanovic** [piotrturski/zohhak#12]
hi,

first of all: thank you for your efforts, i really enjoy writing parameterized tests with zohhak.
i was just wondering how to pass the `String` `"null"` into a method with a `String` parameter, as null is (case insensitive) interpreted as `NULL`. Is there any easy way to achieve this?

Heres a fictive example:
```java
@TestWith({
            "null, false", // -> null
            "null, true"  // -> the string null (but how?)
    })
    public void testOptional(String content, boolean expected){
        Assert.assertEquals(expected, Optional.ofNullable(content).isPresent());
    }
```
thanks in advance,
aleks

**Comment by piotrturski** [comment]
maybe docs can help: https://github.com/piotrturski/zohhak/blob/master/Full-Guide.md#null
does it solve your problem?

**Comment by codejanovic** [comment]
nope, I was not able to find an exception for passing null as a value. I thought you could tell me :D

**Comment by piotrturski** [comment]
you asked:

> how to pass the String "null" into a method with a String parameter

the link i gave you shows how this can be done:
```
@TestWith(" 'null' ")
public void notNullTest(String notNull) {
    assertThat(notNull).isEqualTo("null");
}
```

**Comment by codejanovic** [comment]
Well, i read the guide like 5 times and did not see it. So you simply could have posted this in the first comment ;-) I think the term 

> currently there is no possibility to change pattern recognized as null

let me overread the second code example in that section. Would you mind extracting it to another section with its own title "null as a value"? This should make it much more visible in my opinion.

**Comment by piotrturski** [comment]
done. plz tell if it's more visible now

**Comment by codejanovic** [comment]
Yes, I think its more visible now, thanks! The future will show if this will also apply to others ^^
