### ISSUE TITLE
Link in MD file shows to google code

### ISSUE THREAD

**Issue by liptga** [piotrturski/zohhak#13]
Hi!

Thanks for the great project. In your readme the following link does not work: http://wiki.zohhak.googlecode.com/git/img/eclipse_run.gif 

You made me actually laugh :) 

The text before: "No plugin needed. Just run and you'll see:" then I clicked -> Not found. Pretty funny :D

Thanks and kind regards,

Gábor

**Comment by piotrturski** [comment]
finally someone made me fix it :) thx
