### ISSUE TITLE
Allow ZohhakRunner to initialize at runtime

### ISSUE THREAD

**Issue by oleksandr-yatsuk** [piotrturski/zohhak#15]
There is an issue to use ZohhakRunner in test classes which already run with another test runner.
It would be great if the support of ZohhakRunner initialization at runtime was added.

The example is: MockitoAnnotations.initMocks(this);

**Comment by piotrturski** [comment]
unfortunately i couldn't find a way to do it. AFAIK junit4 treats setting up fields fundamentally different than calculating methods to be run. if you know how to do it, feel free to send a pull request. if not, don't expect this feature to be solved, sorry :(
from what i've seen on github, some companies take the ZohhakRunner (which is designed to be pretty small and simple) and bake it into their own runner that mixes functionality from all the runners they need
