### ISSUE TITLE
TestsClass hangs when run in IntelliJ

### ISSUE THREAD

**Issue by jason-womack** [piotrturski/zohhak#4]
When running a test annotated with the ZohhakRunner.class in IntelliJ, the tests all complete, but the class never completes.  It just hangs with a spinning wheel, rather than showing a status badge of complete or fail.
![screen shot 2015-01-16 at 9 50 29 am](https://cloud.githubusercontent.com/assets/918033/5781081/00573a00-9d6d-11e4-9573-c9702d0368ad.png)

Tested with Zohhak 1.0.1 and 1.1.0 and IntelliJ 13 and 14.

**Comment by piotrturski** [comment]
could you plz provide also your version of junit?

**Comment by piotrturski** [comment]
problem occurs only when @TestWith is mixed with @Test in the same class. only class level doesn't get 'finished' status. package and project level has correct status. intellij marks tests as 'done' but doesn't change the icon

**Comment by piotrturski** [comment]
not sure if i can do anything with it. intellij reports `Done 108 of 108 (in 0,988 s)` and `Process finished with exit code 0` yet still displays 'pending' icon.
i created an issue in intellij's issue tracker: https://youtrack.jetbrains.com/issue/IDEA-135907 hopefully there will be some feedback

**Comment by jason-womack** [comment]
Thanks for looking into this.

**Comment by piotrturski** [comment]
looks like guys from intellij fixed the problem. it works in [IntelliJ IDEA 15 EAP 142.2670](http://blog.jetbrains.com/idea/2015/06/intellij-idea-15-eap-142-2670-is-available/)

**Comment by piotrturski** [comment]
fixed in intellij 15
