### ISSUE TITLE
TestRule classes don't receive method annotations in Description, when using @TestWith

### ISSUE THREAD

**Issue by Cornel-Craveta** [piotrturski/zohhak#7]
1. If I use my own TestRule rule in a ZohhakRunner test,
2. And if I annotate the '@TestWith' methods with some additional annotation, let's say '@IgnoreInSomeConditions'.

Then I expected that the Description object received by TestRule.apply(Statement, Description) will return my annotation '@IgnoreInSomeConditions' when I call Description.getAnnotations, but it does not happen. If I use a MethodRule instead of TestRule, I receive that annotation, but I have to use TestRule.

**Comment by piotrturski** [comment]
can you provide code that reproduces that error? any link to github or push request? it should speed-up solving the issue

**Comment by Cornel-Craveta** [comment]
I put an example at https://github.com/Cornel-Craveta/zohhak.git 
Testet with java 1.8.0_65 on Mac OS X.
